#           Файл конфигурации
#   Скопируйте в config.ini и укажите свои значения
#   Чувствительные данные вынесены в .env
#Настройки базы данных
[dataBase]
db_login = "${DB_LOGIN}"
db_password = "${DB_PASSWORD}"
db_host = "${DB_HOST}"
db_name = "${DB_NAME}"
db_charset = "${DB_CHARSET}"
db_driver = "${DB_DRIVER}"

#DateTime config
#-- F j, Y, g:i a                 // March 10, 2001, 5:16 pm
#-- m.d.y                         // 03.10.01
#-- j, n, Y                       // 10, 3, 2001
#-- Ymd                           // 20010310
#-- h-i-s, j-m-y, it is w Day     // 05-16-18, 10-03-01, 1631 1618 6 Satpm01
#-- D M j G:i:s T Y               // Sat Mar 10 17:16:18 MST 2001
#-- H:i:s                         // 17:16:18
#-- Y-m-d H:i:s                   // 2001-03-10 17:16:18 формат MySQL DATETIME
[dateTime]
default_timezone = "${DEFAULT_TIMEZONE}"
date_TPL = "${DATE_TPL}"
time_TPL = "${TIME_TPL}"

#test todo
[mode]
active_mode = "${ACTIVE_MODE}"

# Настройки сессий
[sessionHandler]
; Доступные значения: 'files', 'redis'
save_session_handler = "${SAVE_SESSION_HANDLER}"
; Настройки для Redis
save_session_path_method = "${SAVE_SESSION_PATH_METHOD}"
save_session_path_host = "${SAVE_SESSION_PATH_HOST}"
save_session_path_port = "${SAVE_SESSION_PATH_PORT}"
; Пароль для Redis (оставьте пустым, если пароль не требуется)
save_session_path_auth = "${SAVE_SESSION_PATH_AUTH}" 