#           Файл конфигурации
#   Скопируйте в config.ini и укажите свои значения
#Настройки базы данных
[dataBase]
db_login = "Vampqwe"
db_password = "Hdva4r81"
db_host = "127.0.1.31"
db_name = "inventory"
db_charset = "utf8mb4"
db_driver = "mysql"

#DateTime config
#-- F j, Y, g:i a                 // March 10, 2001, 5:16 pm
#-- m.d.y                         // 03.10.01
#-- j, n, Y                       // 10, 3, 2001
#-- Ymd                           // 20010310
#-- h-i-s, j-m-y, it is w Day     // 05-16-18, 10-03-01, 1631 1618 6 Satpm01
#-- D M j G:i:s T Y               // Sat Mar 10 17:16:18 MST 2001
#-- H:i:s                         // 17:16:18
#-- Y-m-d H:i:s                   // 2001-03-10 17:16:18 формат MySQL DATETIME
[dateTime]
default_timezone = "Europe/Minsk"
date_TPL = "Y-m-d"
time_TPL = "H:i:s"

#test todo
[mode]
active_mode = "MODE_DB"

# Настройки сессий
[sessionHandler]
; Доступные значения: 'files', 'redis'
save_session_handler = file
; Настройки для Redis
save_session_path_method = "tcp"
save_session_path_host = "127.0.1.55"
save_session_path_port = "6379"
; Пароль для Redis (оставьте пустым, если пароль не требуется)
save_session_path_auth = "" 