; Test config file
[db]
host = localhost
name = inventory
login = testuser
password = testpass
charset = utf8
driver = mysql

[datetime]
default_timezone = Europe/Minsk
date_TPL = Y-m-d
time_TPL = H:i:s
