CREATE DATABASE IF NOT EXISTS vampqwe CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS 'vampqwe'@'%' IDENTIFIED BY 'secret';
GRANT ALL PRIVILEGES ON vampqwe.* TO 'vampqwe'@'%';
FLUSH PRIVILEGES;
